name: lxp_ithub_lazy_loading
description: A new Flutter package project.
version: 2.0.0+2
homepage: https://github.com/meg4cyberc4t/lxp_ithub_lazy_loading

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  json_serializable: ^6.4.1
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
